// Code generated by wit-bindgen-go. DO NOT EDIT.

package request

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasm:cv".

//go:wasmexport wasm:cv/request#process
//export wasm:cv/request#process
func wasmexport_Process(image0 uint32) (result0 uint32) {
	image := cm.Reinterpret[Mat]((uint32)(image0))
	result := Exports.Process(image)
	result0 = cm.Reinterpret[uint32](result)
	return
}
