// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package request represents the exported interface "wasm:cv/request".
//
// request resource is a request from host for guest module to process an image.
package request

import (
	"wasmcv.org/wasm/cv/mat"
)

// Mat represents the exported type alias "wasm:cv/request#mat".
//
// See [mat.Mat] for more information.
type Mat = mat.Mat
