// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package imports represents the world "wasm:cv/imports".
//
// wasmCV is a WebAssembly guest module interface for computer vision based on OpenCV.
package imports
